/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Vedge API
 * 암표 방지 티켓 예매 서비스 Vedge API 문서
 * OpenAPI spec version: 1.0
 */
import type { CreateCellDtoType } from './createCellDtoType';

export interface CreateCellDto {
  /** 좌석의 행 인덱스 */
  rowIndex: number;
  /** 좌석 타입 (SEAT/EMPTY/AISLE) */
  type: CreateCellDtoType;
}
