/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Vedge API
 * 암표 방지 티켓 예매 서비스 Vedge API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 열 타입 (SEAT/EMPTY/AISLE)
 */
export type CreateSeatColumnDtoType = typeof CreateSeatColumnDtoType[keyof typeof CreateSeatColumnDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateSeatColumnDtoType = {
  SEAT: 'SEAT',
  EMPTY: 'EMPTY',
  AISLE: 'AISLE',
} as const;
