/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Vedge API
 * 암표 방지 티켓 예매 서비스 Vedge API 문서
 * OpenAPI spec version: 1.0
 */
import type { CreateSeatColumnDto } from './createSeatColumnDto';

export interface CreateSectionDto {
  /** 통로 인덱스 배열 */
  aisleIndex: number[];
  /** 열 목록 */
  columns: CreateSeatColumnDto[];
  /** 구역 행 인덱스 */
  rowIndex: number;
}
