/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Vedge API
 * 암표 방지 티켓 예매 서비스 Vedge API 문서
 * OpenAPI spec version: 1.0
 */
import type { CreateCellDto } from './createCellDto';
import type { CreateSeatColumnDtoType } from './createSeatColumnDtoType';

export interface CreateSeatColumnDto {
  /** 좌석 목록 */
  cells: CreateCellDto[];
  /** 열 인덱스 */
  columnIndex: number;
  /** 열 타입 (SEAT/EMPTY/AISLE) */
  type: CreateSeatColumnDtoType;
}
