/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Vedge API
 * 암표 방지 티켓 예매 서비스 Vedge API 문서
 * OpenAPI spec version: 1.0
 */

export interface LockSeatDto {
  /** 예매자 이름 */
  name: string;
  /** 잠금 처리할 좌석 ID 배열 */
  seatIds: string[];
}
