/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Vedge API
 * 암표 방지 티켓 예매 서비스 Vedge API 문서
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  /** 이름 */
  name: string;
  /** 휴대폰 번호 */
  phoneNumber: string;
  /** 사용자 권한 */
  role: string;
}
