/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Vedge API
 * 암표 방지 티켓 예매 서비스 Vedge API 문서
 * OpenAPI spec version: 1.0
 */

export interface ReserveTicketDto {
  /** 예매 매수 */
  count: number;
  /** 공연 일정 ID */
  eventScheduleId: string;
  /** 좌석 정보 (JSON string) */
  seatMap: string;
}
