/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Vedge API
 * 암표 방지 티켓 예매 서비스 Vedge API 문서
 * OpenAPI spec version: 1.0
 */

export type UpdateEventDtoCategory = typeof UpdateEventDtoCategory[keyof typeof UpdateEventDtoCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateEventDtoCategory = {
  CONCERT: 'CONCERT',
  MUSICAL: 'MUSICAL',
  EXHIBITION: 'EXHIBITION',
  EVENT: 'EVENT',
} as const;
