/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Vedge API
 * 암표 방지 티켓 예매 서비스 Vedge API 문서
 * OpenAPI spec version: 1.0
 */

export type UploadControllerUploadTicketBody = {
  /** 업로드할 티켓 이미지 파일 */
  file?: Blob;
};
